name: Main Workflow
on:
  pull_request:
    branches: [main, next-minor]
  push:
    branches: [main]
jobs:
  build:
    name: Actions
    strategy:
      matrix:
        node-version: [16, 17]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - run: node --version
      - run: npm ci
      - run: npm run format
      - run: npm run lint
      - run: npm run package
      - run: npm run test

