name: Main Workflow
on:
  pull_request:
    branches: [main, next-minor]
  push:
    branches: [main]
jobs:
  build:
    name: Actions
    strategy:
      matrix:
        node-version: [16, 17]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            ./package-lock.json
      - uses: actions/cache@v3
        id: cache-packages
        with:
          path: packages/**
          key: ${{ runner.os }}-${{ hashFiles('packages/*') }}
      - run: node --version
      - run: npm i
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
      - run: npm run format
      - run: npm run lint
      - run: npm run package
        if: steps.cache-packages.outputs.cache-hit != 'true'
      - run: npm run test
