name: Publish Workflow
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn --immutable
      - run: yarn run format
      - run: yarn run lint
      - run: yarn run package
      - run: yarn run test
      - run: yarn run prepare:release
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          yarn run pub --dry-run
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
